#Version del docker compose
version: "3.3"

services:
    node-seguridad:
        #Contenedor del Frontend de la aplicación, NO ejecuta código de backend
        build: 
            context: .
            #args: 
                #- config=transven
        container_name: node-seguridad
        restart: always
        #volumes:
            # Los archivos del front deben copiarse en la carpeta /frontend
            #- ./site:/app
            #- ./nginx-custom.conf:/etc/nginx/conf.d/default.conf
        ports:   
            - $PORT:$PORT
        networks:
            - webnet            
        environment:
            - MYSQL_SERVER=$MYSQL_SERVER
            - MYSQL_PORT=$MYSQL_PORT
            - MYSQL_DB=$MYSQL_DB
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PW=$MYSQL_PW
            # si se necesita trabajar con la base de datos local solo cambiar el valor de la variable DEPLOYMENT, no borrarla
            - DEPLOYMENT=dev
            - PORT=$PORT
            - JWT_SECRET=$JWT_SECRET
        working_dir: /app
        command: bash -c "npm start"
    
networks:
    webnet:
